# This workflow will test and check quality of the code

name: test-and-code-quality

on:
  push:
    branches:
      - master
      - test-cov-updatedep

env:
  PYTHON_VERSION: 3.11
  POETRY_VERSION: 2.4.0

jobs:
  test-cov:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Define the versions you want to test against
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: $POETRY_VERSION
      - name: Install the project dependencies
        run: poetry install
      - name: Run tests
        run: poetry run pytest --cov=./ --cov-branch --cov-report=xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Install poetry
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: $POETRY_VERSION
      - name: Install dependencies
        run: poetry install
      - name: Run black
        run: poetry run black . --check
      #- name: Run isort
      #  run: poetry run isort . --check-only
      #- name: Run flake8
      #  run: poetry run flake8 .
      #- name: Run bandit
      #  run: poetry run bandit .
      #- name: Run saftey
      #  run: poetry run safety check
