# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [published, edited]

permissions:
  contents: read

env:
  PYTHON_VERSION: 3.11
  POETRY_VERSION: 2.4.0

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"  # Read python version from a file pyproject.toml
      - name: Install poetry
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: $POETRY_VERSION
      - name: Build release distributions
        run: |
          # NOTE: put your own distribution build steps here.
          poetry lock
          poetry install
          poetry build
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    # Dedicated environments with protections for publishing are strongly recommended.
    # For more information, see: https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#deployment-protection-rules
    environment:
      name: testpypi
      # OPTIONAL: uncomment and update to include your PyPI project URL in the deployment status:
      # url: https://test.pypi.org/project/pretty-confusion-matrix/
      #
      # ALTERNATIVE: if your GitHub Release name is the PyPI project version string
      # ALTERNATIVE: exactly, uncomment the following line instead:
      url: https://test.pypi.org/project/pretty-confusion-matrix/${{ github.event.release.name }}

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          verbose: true
          repository-url: https://test.pypi.org/project/pretty-confusion-matrix/
